### ISSUE TITLE
Issue with Directory Path Containing Question Mark (?) in context_prompt

### ISSUE THREAD

**Issue by yicheng-2019** [lucazanella/lavad#17]
I would like to express my sincere appreciation and admiration for your paper and repositories, with a deep understanding of the implementation of combining LLM, MLLM for downstream video detection tasks.

However, I have encountered an issue in src/models/llm_anomaly_scorer.py. When creating a directory to save scores, if the context_prompt path contains a question mark (?), it results in file creation problems. I have faced this issue both during local testing and when running on the server. Removing the question mark from the context_prompt appears to resolve the problem.

Does removing the question mark (?) from the context_prompt directory name affect the final prediction results or the overall functionality of the script in any way? Or is there a method to retain the question mark in the context_prompt while avoiding this file creation issue? For example, could the script automatically sanitize or replace special characters in the directory path to prevent such errors?

Problematic Code：
```python
(lavad_new) qiuyc@Precision-3650-Tower:~/code/lavad$ bash slurm/ucf_crime/04_query_llm_3090.sh
Processing index: opt-6.7b-coco+opt-6.7b+flan-t5-xxl+flan-t5-xl+flan-t5-xl-coco
Traceback (most recent call last):
  File "/home/qiuyc/anaconda3/envs/lavad_new/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/qiuyc/anaconda3/envs/lavad_new/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/qiuyc/code/lavad/src/models/llm_anomaly_scorer.py", line 295, in <module>
    run(
  File "/home/qiuyc/code/lavad/src/models/llm_anomaly_scorer.py", line 208, in run
    output_scores_dir.mkdir(parents=True, exist_ok=True)
  File "/home/qiuyc/anaconda3/envs/lavad_new/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
OSError: [Errno 22] Invalid argument: '/media/qiuyc/IPSI/datasets/ucf_crime_lavad_test/scores/raw/llama-2-7b-chat/opt-6.7b-coco+opt-6.7b+flan-t5-xxl+flan-t5-xl+flan-t5-xl-coco/_000_if_you_were_a_law_enforcement_agency,_how_would_you_rate_the_scene_described_on_a_scale_from_0_to_1,_with_0_representing_a_standard_scene_and_1_denoting_a_scene_with_suspicious_activities?'
```

**Comment by lucazanella** [comment]
Hi, thank you very much, I appreciate it!

In this case, I recommend keeping the question mark in the context prompt and changing the name of the output directory. As shown in [slurm/ucf_crime/04_query_llm.sh](https://github.com/lucazanella/lavad/blob/1ad46c666d1b3cfb262f3dd84769acf873285056/slurm/ucf_crime/04_query_llm.sh#L37), the output directory name is generated using a unique ID composed of the Slurm job array ID, the task array ID, and the first 243 characters of the prompt (with spaces replaced by underscores). If you are using slurm, you can avoid the problems you experienced by defining `dir_name` like this:

`dir_name=$(printf "%s_%03d" "$SLURM_ARRAY_JOB_ID" "$SLURM_ARRAY_TASK_ID")`

Otherwise, you can generate a unique directory name (unless you run experiments faster than one per millisecond) based on the current timestamp with:

`dir_name=$(date +"%Y-%m-%d_%H-%M-%S-%3N")`

You will also need to modify `dir_name` following this logic in the following scripts. Let me know if this helps!

**Comment by yicheng-2019** [comment]
Thank you very much for your response. 
Because I have not used Slurm tools before, and initially thought your program was designed to run using Shell scripts.

If possible, could you please provide instructions on how to use Slurm to execute the program? I would greatly appreciate your assistance.

**Comment by lucazanella** [comment]
Sorry for the late reply! If you're using a cluster with Slurm, you can run any script with `sbatch <script>`, where `<script>` is the name of the script file you want to run. However, you don't have to use Slurm to run the scripts. I've included the Slurm scripts I used to get the results in the `slurm/` folder, but you can just use the scripts in the `scripts/` folder instead. Just make sure to update some variables like `dataset_dir` and `fps`.

**Comment by yicheng-2019** [comment]
Thank you for your reply. Now, I have completed the full testing process of the UCF-Crime dataset using Bash. This is a great repository.

**Comment by lucazanella** [comment]
I'm happy to hear that, thank you! :)
