### ISSUE TITLE
Congrats on the nice work!

### ISSUE THREAD

**Issue by wyzjack** [lucazanella/lavad#2]
Congrats on the nice work!

I am writing to ask about when you are planning to release your code? Thanks so much.

Also, is it possible to share your extracted CLIP features on UCF Crime and XD-Violence dataset? Thanks in advance.

I would appreciate it very much if you could reply.

**Comment by lucazanella** [comment]
Hi, thank you for your interest in our work! 

I take this opportunity to apologise to everyone who is waiting for the code to be released. I currently have very limited bandwidth due to an impending deadline. I will release the code by the end of this month at the latest. I will also release the data, including the captions, the temporal summaries, and the indexes containing their text embeddings. For this work, I did not store the pre-extracted image/video features, but if you are interested in the CLIP features for UCF-Crime and XD-Violence you can find them in this other [repository](https://github.com/luca-zanella-dvl/AnomalyCLIP?tab=readme-ov-file#pre-extracted-features). However, these features come from a CLIP ViT/B, whereas I used ImageBind's image and video encoder for this work.

**Comment by wyzjack** [comment]
Great, thanks so much for letting me know!
