### ISSUE TITLE
llama-2-13b-chat

### ISSUE THREAD

**Issue by JaneShiys** [lucazanella/lavad#6]
Hi,I encountered an issue while running slurm/<dataset>/04_query_llm.sh. Could you tell me what the directory tree under libs/llama looks like after downloading llama-2-13b-chat? I really appreciate your help.

**Comment by lucazanella** [comment]
Hi, sure! Please note that the pre-trained model is in `libs/llama/llama-2-13b-chat`, while the tokenizer is in `libs/llama`. Let me know if this helps! Otherwise, let me know how I can help.
![Screenshot from 2024-07-03 17-04-07](https://github.com/lucazanella/lavad/assets/28778129/27cbffe5-7e16-41e4-8b38-c25d39f8b971).

**Comment by JaneShiys** [comment]
Thank you very much! I had  placed the tokenizer under libs/llama/llama-2-13b-chat. With your help, I have now moved it to the correct location, and the program is running.

**Comment by lucazanella** [comment]
Great to hear! :)

**Comment by Puqi7** [comment]
Hello, guys. I did not find the pre-trained model in libs/llama/llama-2-13b-chat. Could you please tell me where it is? 
<img width="590" alt="Screenshot 2024-11-07 at 12 54 03 PM" src="https://github.com/user-attachments/assets/66c55e1d-d3cd-4326-aa5f-b9c08f6fdcfc">
