### ISSUE TITLE
What is frame_interval in scripts/01_caption.sh?

### ISSUE THREAD

**Issue by ut21** [lucazanella/lavad#8]
Hey, as mentioned could you please explain what frame_interval hyper parameter refers to? I am trying to run the model on my custom dataset which has 10 fps videos, should I change the frame_interval value? Thank you for the nice code and work.

**Comment by luca-zanella-dvl** [comment]
Hi, thank you! We chose to process 1 frame every `frame_interval` to reduce the processing time. For our videos, which were approximately 30 fps, we used a `frame_interval` of 16, which means we processed about 1 frame every 0.5 seconds. You can use a frame interval of 1 for your videos if the computation is fast enough. Otherwise, consider using a `frame_interval` of 5.

**Comment by lucazanella** [comment]
Hi, thank you! We chose to process 1 frame every `frame_interval` to reduce the processing time. For our videos, which were approximately 30 fps, we used a `frame_interval` of 16, which means we processed about 1 frame every 0.5 seconds. You can use a frame interval of 1 for your videos if the computation is fast enough. Otherwise, consider using a `frame_interval` of 5.

**Comment by ut21** [comment]
Thank you very much for the clarification
