### ISSUE TITLE
Does scripts/03_clean_captions.sh only process videos of the same length? 

### ISSUE THREAD

**Issue by ut21** [lucazanella/lavad#9]
Hey,
In scripts/03_clean_captions.sh these are the parameters:
```
batch_size=32
frame_interval=16
fps=30  # Change this to the frame rate of your videos
clip_duration=10
num_samples=10
num_neighbors=1
```
does this mean that the length of each video must be the same and equal to clip_duration? Also, how is num_samples being used by the python script, and do I need to configure it depending on my dataset? Lastly, I have an ensemble dataset with two different FPSs for videos, is there a way to work around this? Thank you so much!

**Comment by lucazanella** [comment]
Hi,

The script can process videos of arbitrary length. `clip_duration` defines the length in seconds of the temporal windows for summarizing captions in the LLM-based anomaly scoring step (see 04_query_llm.sh). `num_samples` specifies the number of frames to sample uniformly within each temporal window, whose clean captions will be used to query the LLM. You need to adjust them according to your needs. Adjusting `clip_duration` changes how the score of each frame is affected by the previous and future `clip_duration // 2` seconds. By setting `num_samples` equal to `clip_duration`, the LLM will use one caption per second for the temporal summary.

For datasets with videos with different frame rates, instead of setting the FPS manually, you can modify the scripts to calculate it dynamically, for example using OpenCV.

**Comment by ut21** [comment]
Thank you very much for the help. I noticed in the UCF crime dataset you linked in the readme the captions and scores are available for only around 300 videos. Is this the test split of the UCF dataset? Is it please possible to provide these for the full UCF dataset, because running the slurm scripts is taking a very long time even on multiple GPUs and regularly gets killed due to Out of Memory errors. Thank you very much

**Comment by lucazanella** [comment]
I'm glad to help! 

The files I uploaded for UCF-Crime and XD-Violence are for the videos of the respective test sets. Unfortunately, I don't have similar files for the training set.

**Comment by ut21** [comment]
No worries! Thanks for the help, and congratulations on the brilliant work

**Comment by lucazanella** [comment]
Thank you very much! :)
